### ISSUE TITLE
mbed-usb-device-serial test failing

### ISSUE THREAD

**Issue by multiplemonomials** [mbed-ce/mbed-os#54]
In CI, this test gets halfway through, then fails with:
```
[1663456332.04][CONN][RXD] >>> Running case #3: 'CDC RX single bytes concurrent'...
[1663456332.09][CONN][INF] found KV pair in stream: {{__testcase_start;CDC RX single bytes concurrent}}, queued...
[1663456332.17][CONN][INF] found KV pair in stream: {{send_single;0}}, queued...
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python3.9/threading.py", line 954, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.9/threading.py", line 892, in run
    self._target(*self._args, **self._kwargs)
  File "/home/jenkins/workspace/mbed-os-ce/drivers/usb/tests/TESTS/host_tests/usb_device_serial.py", line 215, in send_data_sequence
    mbed_serial.reset_input_buffer()
  File "/home/jenkins/.local/lib/python3.9/site-packages/serial/serialposix.py", line 683, in reset_input_buffer
    self._reset_input_buffer()
  File "/home/jenkins/.local/lib/python3.9/site-packages/serial/serialposix.py", line 677, in _reset_input_buffer
    termios.tcflush(self.fd, termios.TCIFLUSH)
termios.error: (5, 'Input/output error')
```

I have also seen:
```
[1663454516.95][CONN][RXD] >>> Running case #3: 'CDC RX single bytes concurrent'...
[1663454517.01][CONN][INF] found KV pair in stream: {{__testcase_start;CDC RX single bytes concurrent}}, queued...
[1663454517.09][CONN][INF] found KV pair in stream: {{send_single;0}}, queued...
[1663454517.64][CONN][RXD] <greentea test suite>:423::FAIL: Expected 255 Was 94
[1663454517.69][HTST][INF] TEST ERROR: Write timeout
[1663454517.69][HTST][INF] __notify_complete(False)
[1663454517.69][HTST][INF] __exit_event_queue received
[1663454517.69][HTST][INF] test suite run finished after 5.80 sec...
```

This happens with both the LPC1768 and STM32F4 targets so I assume it's a target-agnostic issue, but can't really say for sure.

**Comment by multiplemonomials** [comment]
On NRF52840, the test passes half the time, and the other half of the time you get the "Expected 255 Was 94" error.
